[project]
name = "tab-api-mcp"
version = "0.1.0"
description = "TAB API MCP Server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.2.1",
    "python-dotenv>=1.0.1",
    "uvicorn>=0.29.0",
]